services:
  app:
    image: dev-todo-frontend
    build:
      context: todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3000
    container_name: dev-todo-frontend
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      # ro means read only
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for frontend container to be started

