version: '3.8'

# MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database npm run dev
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container id/name>

# run with: docker compose --env-file .env -f docker-compose.dev.yml up
# down with: docker compose -f docker-compose.dev.yml down --volumes
# remove volume with: sudo rm -rf mongo_data

services:
  mongodb:
    image: mongo:latest
    ports:
      - 3456:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      # bound mounts https://docs.docker.com/storage/bind-mounts/
      # a type of volume, remove with --volume when running docker compose down
      # changes in either file reflects the other

      # js files in docker-entrypoint-initdb.d are run when first starting the container
      # <local file>:<file in container>
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    # --appendonly yes: enable AOF persistence
    # --loglevel warning: log only warnings and errors
    command: redis-server --appendonly yes --loglevel warning
    volumes:
      - redis_data:/data


volumes:
  mongo_data:
  redis_data:
