version: '3.8'

services:
  app:
    image: patientor-frontend
    build:
      context: ./patientor-main
      # omitted dockerfile field defaults to Dockerfile
    container_name: patientor-frontend
    depends_on:
      - server
  server:
    image: patientor-backend
    build:
      context: ./patientor-backend
      # omitted dockerfile field defaults to Dockerfile
    container_name: patientor-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
