version: '3.8'

services:
  app:
    image: dev-patientor-frontend
    build:
      context: ./patientor-main
      dockerfile: dev.Dockerfile
    volumes:
      - ./patientor-main:/usr/src/app
    container_name: dev-patientor-frontend
    depends_on:
      - server
  debug-helper:
    image: busybox
  server:
    image: dev-patientor-backend
    build:
      context: ./patientor-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./patientor-backend:/usr/src/app
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
